- yarn.lock
> enh: update yarn dependencies

- packages/components/NavBar.tsx
Adicionando de volta Dark Theme.
> removi sem querer dando um `push` direto da `main` 🙈
- Reparem bem como são usados as propriedades e os components do chakra
- @frattezi removi aquele `useMemo`, achei um jeitinho mais bonito de fazer
> fix: add dark theme back

- yarn.lock
Update yarn deps
- lembra de dar yarn 
- it closes #31
> enh: upgrade yarn deps

- .eslintrc.yml
- package.json
- packages/components/CallToActionSection.tsx
- packages/components/Layout.tsx
- packages/components/MentoringSection.tsx
- packages/components/NotFound.tsx
- packages/components/Section.tsx
- packages/components/WhyItWorksSection.tsx
- yarn.lock
Removi o `Container` do layout e o coloquei em cada página. Dessa forma o bg fica desvinculado do Container, possibilitando fundos que ocupem toda a largura da tela.
> Move Container from Layout

- packages/components/CallToActionSection.tsx
- packages/components/MentoringSection.tsx
- packages/components/RoadmapSection.tsx
- packages/components/WhyItWorksSection.tsx
- packages/features/i18n-context.tsx
- packages/locale/en.yml
- packages/locale/pt.yml
> Refatora todas as keys de traducao para kebab-case
> Refatora as keys e onde elas estao sendo usadas dentro de cada componente
> Refactor translation keys to kebab-case

- packages/components/Footer.tsx
> Resolves [this](https://podcodar.notion.site/Adicionar-_blank-em-links-externos-do-rodape-ate-o-momento-sao-os-2-de-redes-sociais-8993fe2df7224a1d82e6a90487f76f6c)
> Add external link logic to all the links on our footer using booleans. Now we have our social links as external and the support links as internal
> fix: Add external link logic to component

- package.json
- packages/components/Footer.tsx
- packages/config.ts
- packages/locale/en.yml
- packages/locale/pt.yml
- yarn.lock
Buscando fomentar as doações para mantermos as bolsas na comunidade, sugiu-se a necessidade de publicar em nossa pagina o qr code da chave pix para as doaçẽos
> fea: add PIX QR code to footer

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
> Breve descrição das suas mudanças
> Detalhamento, se necessario
- item 1
- item 2
> Deixe algumas notas que possam ser úteis aos revisores
- nota 1
- nota 2
> fix: bind var envs

- packages/components/MemberCard.tsx
- packages/utils/mocApi.json
- pages/team.tsx
Esta pull request implementa o card de membros
- Criei o mock para simular os dados nescessários para a renderização do card 
It closes #76
> Create Member card 

- packages/components/MemberCard.tsx
- yarn.lock
Update package dependencies
- run `yarn upgrade`
- update props
> enh: update dependencies

- packages/components/Layout.tsx
- pages/index.tsx
fixes modal not opening at /teams
as modal is opened at Navbar component , i moved the modal component from index page to Layout component  so that is always stays with the Navbar and not only at index page
closes #112
> fix modal not opening at /team

- package.json
- pages/api/_middleware.ts
- yarn.lock
This PR updates project dependencies with `yarn upgrade`
- update deps versions
- replace `Buffer` by `atob` from middleware as Next Edge doesn't accept it - [ref](https://nextjs.org/docs/api-reference/edge-runtime)
- remove useless type definitions
This close #115
> Update project dependencies

- packages/components/RoadmapSection.tsx
- packages/components/TestimonialSection.tsx
- packages/features/i18n-context.tsx
- packages/locale/en.yml
- packages/locale/pt.yml
- pages/index.tsx
creates and renders new TestimonialsSection component
- title uses i18n
- title follows same parameters as the others
- uses the /Section premade component following same patterns 
closes #123
> Create testimonials section

- packages/components/MentoringSection.tsx
- packages/locale/en.yml
- packages/locale/pt.yml
> texts remover: personalized mentoring, individual mentoring
> Add texts : trail mentoring, market mentoring
> changes made to the pt.yml and en.yml text files, updating the mentorship texts.
> Before:
> After:
> Update mentoring texts

- packages/components/RoadmapSection.tsx
- packages/components/TechSection.tsx
- packages/components/TestimonialSection.tsx
- packages/config/firebase.ts
- packages/entities/testimonials.ts
- packages/services/testimonials.ts
- pages/index.tsx
this PR integrate and returns list of testimonials as props
- create integration of testimonials section with db
- returns list of testimonials as properties
close: #126
> Integrate and consume data from db

- packages/components/TestimonialSection.tsx
changes testimonials from grid style to carousel 
- inpired by https://codesandbox.io/s/chakra-card-slider-62lsm8?file=/src/app.js
- closes #134
> make testimonials carousel

- .github/pull_request_template.md
- .github/workflows/tests.yml
- packages/utils/classes.test.ts
- packages/utils/classes.ts
- packages/utils/types.ts
This PR implements some improvements to the `classes` utils
- ref: rewrite it into a "less-functional" approach
- fea: ignore conflicting tokens
- enh: update unit tests
- enh: run unit tests as a gh action
> [ref] improving `classes` to ignore conflicting classes

- .github/workflows/quality-gateway-pull-request.yml
This task implements CI pipelines to integrate with code analysis tools
- fea: add static code analyzer (biome + reviewdog)
- ref: cleanup quality-gateway-pull-request.yml
- https://biomejs.dev/recipes/continuous-integration/
- https://biomejs.dev/recipes/continuous-integration/#third-party-actions
> If necessary, add screenshots or gifs to illustrate the changes.
This closes #185
> [fea] setup code analysis tool

- app/not-found.tsx
- app/team/page.tsx
- packages/components/CallToActionSection.tsx
- packages/components/Footer.tsx
- packages/components/MentoringSection.tsx
- packages/components/RoadmapSection.tsx
- packages/components/Section.tsx
- packages/components/TestimonialSection.tsx
- packages/components/WhyItWorksSection.tsx
The refactoring replaces Chakra UI with Daisy UI and Tailwind, simplifying styling, improving consistency, and reducing dependencies, leading to more efficient and maintainable code.
- *Section:* In the Section, className and id properties were added for improved customization. Padding was updated to use Tailwind CSS classes, enhancing consistency. The classes function was implemented to manage and combine styles efficiently.
- *Footer:* The background color was adjusted from `#0a1523` to `bg-neutral-950`. The original color would require adjustments in the theme, but after discussions with the owner, it was decided to use an approximate color for easier transition.
- *MentoringSection:* The padding was modified to use Tailwind classes, replacing Chakra UI properties.
- …
> [ref] Section Component

- next.config.js
- packages/components/TestimonialSection.tsx
This task is refactoring the `TestimonialSection` to not depend on chakra-ui.
old:
new:
This closes #208
> [ref] Migrate TestimonialSection component

- biome.json
- packages/components/Layout.tsx
- packages/components/Link.tsx
- packages/components/MemberCard.tsx
- packages/components/NavBar.tsx
- packages/components/RoadmapSection.tsx
- packages/components/SocialIconLinks.tsx
- packages/components/ToggleLanguage.tsx
- packages/components/ToggleThemeButton.tsx
- packages/features/i18n-context.tsx
This task migrates a few remaining components, such as:
- `Link`
- `NavBar`
- and others
This closes #214
> [ref] migrate remaining components
